AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GetCharityTypesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: GetCharityTypes::GetCharityTypes.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: .
      MemorySize: 256
      Timeout: 30
      Environment:
        Variables:
          DB_HOST: "reusefull.cq0mnx0ystdx.us-east-2.rds.amazonaws.com"
          DB_NAME: "reusefull"
          DB_PORT: "3306"
          DB_REGION: "us-east-2"