/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonateIndexRouteImport } from './routes/donate/index'
import { Route as DonateResultsRouteImport } from './routes/donate/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateIndexRoute = DonateIndexRouteImport.update({
  id: '/donate/',
  path: '/donate/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateResultsRoute = DonateResultsRouteImport.update({
  id: '/donate/results',
  path: '/donate/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate/results': typeof DonateResultsRoute
  '/donate': typeof DonateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate/results': typeof DonateResultsRoute
  '/donate': typeof DonateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate/results': typeof DonateResultsRoute
  '/donate/': typeof DonateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/donate/results' | '/donate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/donate/results' | '/donate'
  id: '__root__' | '/' | '/donate/results' | '/donate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateResultsRoute: typeof DonateResultsRoute
  DonateIndexRoute: typeof DonateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/': {
      id: '/donate/'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate/results': {
      id: '/donate/results'
      path: '/donate/results'
      fullPath: '/donate/results'
      preLoaderRoute: typeof DonateResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateResultsRoute: DonateResultsRoute,
  DonateIndexRoute: DonateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
