name: Deploy to Netlify

on:
  push:
    paths:
      - 'src/**'
      - 'index.html'
      - 'netlify.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # env:
    #  NODE_ENV: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # or any version you prefer

    - name: Install dependencies
      run: npm install

    - name: Fix permissions for Vite
      run: chmod +x ./node_modules/.bin/vite
    
    - name: Build project
      run: npm run build
      
    - name: Deploy to Netlify using API
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      run: |
        # Create a zip file of the dist directory
        cd dist
        zip -r ../deploy.zip .
        cd ..
        
        # Deploy using Netlify API
        curl -H "Authorization: Bearer $NETLIFY_AUTH_TOKEN" \
             -H "Content-Type: application/zip" \
             --data-binary @deploy.zip \
             "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys"
